#lang racket/base
;; Turns a machine value into the .machine format: plain S-expressions
;; with every number a finite flonum, so the C# reader never meets exact
;; rationals (3/100) or infinities.
(require racket/path racket/match racket/list "machine.rkt" "map.rkt" "geometry/shape.rkt" "materials.rkt"
         (only-in "planets.rkt" planet-fields))
(provide machine->sexp write-machine-file map->sexp write-map-file)

(define (num who v)
  (unless (and (real? v) (rational? v))
    (error 'machine->sexp "~a must be a finite number, got ~e" who v))
  (exact->inexact v))

(define (value who v)
  (if (or (boolean? v) (symbol? v) (string? v)) v (num who v)))

;; Every number a planet has, resolved, so the C# side needs no preset
;; table: (planet mars (gravity 3.71) (pressure 610.0) (air (o2 0.0017) ...) ...)
(define (planet->sexp p)
  `(planet ,(planet-name p)
           ,@(for/list ([f (planet-fields p)])
               (define key (car f))
               (case key
                 [(name) `(name ,(cadr f))]
                 [(air) `(air ,@(for/list ([g (cdr f)]) (list (car g) (num "planet air" (cadr g)))))]
                 [(molar-mass) `(molar-mass ,(let ([v (cadr f)]) (if v (num "planet molar-mass" v) #f)))]
                 [else `(,key ,@(for/list ([v (cdr f)]) (num (format "planet ~a" key) v)))]))))

(define (loc->sexp loc root)
  (define file (vector-ref loc 0))
  (define shown
    (if (and root (absolute-path? file))
        (path->string (find-relative-path (simple-form-path root) (simple-form-path file)))
        file))
  `(srcloc ,shown ,(vector-ref loc 1) ,(vector-ref loc 2)))

(define (part->sexp p root)
  (define id (part-id p))
  `(part ,id ,(part-kind p)
         (material ,(part-material p))
         (at ,@(for/list ([x (part-at p)]) (num (format "~a position" id) x)))
         (props ,@(for*/list ([kv (part-props p)] [item (prop->items id kv)]) item))
         (ports ,@(for/list ([pt (part-ports p)])
                    (list (port-spec-name pt) (port-spec-kind pt)
                          (num (format "~a port height" id) (port-spec-height pt)))))
         ,(loc->sexp (part-loc p) root)))

;; A generated shape becomes the name of its mesh file (build.rkt writes
;; it to game/meshes/<stem>.glb), its material volume, and the numbers
;; that describe it — a gear's pitch radius, a screw's pitch — so the game
;; never has to measure a mesh to learn them.
(define (prop->items id kv)
  (define v (cdr kv))
  (if (shape? v)
      `((shape ,(shape-kind v))
        (mesh ,(shape-file-stem v))
        (volume ,(num (format "~a shape volume" id) (shape-volume v)))
        ,@(for/list ([axis '(inertia-x inertia-y inertia-z)] [i (shape-inertia v)])
            (list axis (num (format "~a shape ~a" id axis) i)))
        ,@(for/list ([sp (shape-props v)])
            (list (car sp) (value (format "~a shape ~a" id (car sp)) (cdr sp)))))
      (list (list (car kv) (value (format "~a #:~a" id (car kv)) v)))))

;; root: when given, source paths are written relative to it.
(define (machine->sexp m #:root [root #f])
  `(machine ,(machine-name m)
            ,@(if (machine-source m) `((source ,(machine-source m))) '())
            ,@(if (= (machine-ambient m) 20) '() `((ambient ,(num "#:ambient" (machine-ambient m)))))
            ,@(let ([p (machine-planet m)])
                (if (earth-planet? p) '() (list (planet->sexp p))))
            ,@(let ([w (machine-weather m)])
                (if w
                    `((weather (daily ,(weather-daily w))
                               (passes ,@(for/list ([h (weather-passes w)]) (num "weather #:passes" h)))
                               (pass-minutes ,(num "weather #:pass-minutes" (weather-pass-minutes w)))
                               ,@(for/list ([s (weather-storms w)])
                                   `(storm (sol ,(storm-sol s)) (hour ,(num "storm #:hour" (storm-hour s)))
                                           (tau ,(num "storm #:tau" (storm-tau s))) (sols ,(num "storm #:sols" (storm-sols s)))
                                           (settle ,(num "storm #:settle" (storm-settle s)))))))
                    '()))
            ,@(match (machine-sun m)
                [#f '()]
                [(list lat day time) `((sun (latitude ,(num "#:latitude" lat)) (day ,day) (time ,(num "#:time" time))))])
            ,@(for/list ([p (machine-parts m)]) (part->sexp p root))
            ,@(for/list ([p (machine-pipes m)])
                `(pipe ,(pipe-spec-id p)
                       (from ,@(pipe-spec-from p))
                       (to ,@(pipe-spec-to p))
                       (conductance ,(num (format "pipe ~a conductance" (pipe-spec-id p))
                                          (pipe-spec-conductance p)))
                       (jet ,(pipe-spec-jet? p))
                       ,(loc->sexp (pipe-spec-loc p) root)))
            ,@(for/list ([c (machine-connects m)])
                `(connect ,(connect-spec-from c) ,(connect-spec-to c)
                          ,(loc->sexp (connect-spec-loc c) root)))
            ,@(for/list ([r (machine-ropes m)])
                (define id (rope-spec-id r))
                (define (end e) (cons (car e) (for/list ([x (cdr e)]) (num (format "rope ~a end" id) x))))
                `(rope ,id
                       (from ,@(end (rope-spec-from r)))
                       (to ,@(end (rope-spec-to r)))
                       (length ,(num (format "rope ~a #:length" id) (rope-spec-length r)))
                       (over ,@(for/list ([p (rope-spec-over r)])
                                 (for/list ([x p]) (num (format "rope ~a #:over" id) x))))
                       (wind-on ,(rope-spec-wind-on r))
                       (release-deg ,(let ([d (rope-spec-release-deg r)]) (if d (num "rope #:release-deg" d) #f)))
                       (material ,(rope-spec-material r))
                       (diameter ,(num (format "rope ~a #:diameter" id) (rope-spec-diameter r)))
                       (nocked ,(rope-spec-nocked r))
                       (turns ,(rope-spec-turns r))
                       (bar ,(rope-spec-bar r))
                       (mu ,(let ([u (rope-spec-mu r)]) (if u (num (format "rope ~a #:mu" id) u) #f)))
                       ;; a chain of pinned links (issue #31) only: other ropes' clauses stay as they were
                       ,@(if (rope-spec-links r) `((links ,(rope-spec-links r))) '())
                       ,(loc->sexp (rope-spec-loc r) root)))
            ,@(for/list ([i (machine-inflows m)])
                `(inflow ,(inflow-spec-id i) (into ,(inflow-spec-into i))
                         (flow ,(num "inflow #:flow" (inflow-spec-flow i)))
                         ,(loc->sexp (inflow-spec-loc i) root)))
            ,@(for/list ([c (machine-channels m)])
                (define id (channel-spec-id c))
                `(channel ,id (from ,@(channel-spec-from c))
                          (to ,@(let ([t (channel-spec-to c)]) (if (eq? t 'off) '(off) t)))
                          (end ,@(let ([e (channel-spec-end c)]) (if e (for/list ([x e]) (num "channel #:end" x)) '())))
                          (via ,@(for/list ([p (channel-spec-via c)]) (for/list ([x p]) (num "channel #:via" x))))
                          (width ,(num (format "channel ~a #:width" id) (channel-spec-width c)))
                          (length ,(let ([l (channel-spec-length c)]) (if l (num "channel #:length" l) #f)))
                          (onto ,(channel-spec-onto c))
                          ;; a dynamic reach (issue #36) only: steady channels' clauses stay as they were
                          ,@(if (channel-spec-dynamic c)
                                `((dynamic #t) (cells ,(let ([n (channel-spec-cells c)]) (if n (num "channel #:cells" n) #f))))
                                '())
                          ,(loc->sexp (channel-spec-loc c) root)))
            ,@(for/list ([t (machine-triggers m)])
                (define id (trigger-spec-id t))
                (define (nums what l) (if l (for/list ([x l]) (num (format "trigger ~a ~a" id what) x)) '()))
                `(trigger ,id (at ,@(nums "#:at" (trigger-spec-at t))) (size ,@(nums "#:size" (trigger-spec-size t)))
                          (body ,(trigger-spec-body t))
                          (when ,@(let ([w (trigger-spec-when t)])
                                    (if w (list (car w) (cadr w) (caddr w) (num (format "trigger ~a #:when" id) (cadddr w))) '())))
                          (do ,@(for/list ([a (trigger-spec-actions t)])
                                  (list (car a) (cadr a) (num (format "trigger ~a #:do" id) (caddr a)))))
                          ,(loc->sexp (trigger-spec-loc t) root)))
            ,@(for/list ([w (machine-wakes m)])
                (define id (wake-spec-id w))
                (define (term t) (list (car t) (cadr t) (caddr t) (num (format "wake ~a" id) (cadddr t))))
                `(wake ,id (when ,@(map term (wake-spec-terms w)))
                       (join ,(if (wake-spec-all? w) 'and 'or))
                       (limit ,(num (format "wake ~a #:limit" id) (wake-spec-limit w)))
                       (events ,@(map term (wake-spec-events w)))
                       ,(loc->sexp (wake-spec-loc w) root)))
            ,@(for/list ([b (machine-belts m)])
                `(belt ,(belt-spec-id b) ,(belt-spec-a b) ,(belt-spec-b b)
                       (tension ,(num (format "belt ~a #:tension" (belt-spec-id b)) (belt-spec-tension b)))
                       (material ,(belt-spec-material b))
                       ,(loc->sexp (belt-spec-loc b) root)))
            ,@(for/list ([f (machine-follows m)])
                (define id (follow-spec-id f))
                `(follow ,id (lever ,(follow-spec-lever f)) (rope ,(follow-spec-rope f))
                         (from ,(num (format "follow ~a #:from" id) (follow-spec-from f)))
                         (to ,(num (format "follow ~a #:to" id) (follow-spec-to f)))
                         (set ,(follow-spec-target f) ,(follow-spec-field f))
                         (low ,(num (format "follow ~a #:low" id) (follow-spec-low f)))
                         (high ,(num (format "follow ~a #:high" id) (follow-spec-high f)))
                         ,(loc->sexp (follow-spec-loc f) root)))
            ,@(for/list ([j (machine-joints m)])
                (define id (joint-spec-id j))
                (define (nums what l) (for/list ([x l]) (num (format "joint ~a ~a" id what) x)))
                `(joint ,id (kind ,(joint-spec-kind j)) (a ,(joint-spec-a j)) (b ,(joint-spec-b j))
                        (at ,@(nums "#:at" (joint-spec-at j)))
                        (axis ,@(if (joint-spec-axis j) (nums "#:axis" (joint-spec-axis j)) '()))
                        (free ,@(joint-spec-free j))
                        (limit-deg ,(let ([d (joint-spec-limit-deg j)]) (if d (num (format "joint ~a #:limit-deg" id) d) #f)))
                        ,(loc->sexp (joint-spec-loc j) root)))
            ,@(for/list ([c (machine-cylinders m)])
                `(,(if (eq? (cylinder-spec-kind c) 'steam) 'steam-cylinder 'atmospheric-cylinder) ,(cylinder-spec-id c) (piston ,(cylinder-spec-piston c))
                                       (steam-from ,(cylinder-spec-boiler c))
                                       ,@(if (cylinder-spec-crank c) `((crank ,(cylinder-spec-crank c))) '())
                                       ,@(if (cylinder-spec-injection-temperature c)
                                             `((injection-temperature ,(num "cylinder #:injection-temperature" (cylinder-spec-injection-temperature c))))
                                             '())
                                       ,(loc->sexp (cylinder-spec-loc c) root)))
            ,@(for/list ([l (machine-lifts m)])
                `(lift ,(lift-spec-id l) (by ,(lift-spec-by l)) (from ,(lift-spec-from l)) (to ,(lift-spec-to l))
                       (current ,(let ([c (lift-spec-current l)]) (if c (num "lift #:current" c) #f)))
                       (current-from ,(lift-spec-current-from l))
                       ,(loc->sexp (lift-spec-loc l) root)))
            ,@(for/list ([g (machine-meshes m)])
                `(mesh ,(mesh-spec-a g) ,(mesh-spec-b g) ,(loc->sexp (mesh-spec-loc g) root)))
            ,@(for/list ([a (machine-arbors m)])
                `(arbor (parts ,@(arbor-spec-parts a)) ,(loc->sexp (arbor-spec-loc a) root)))
            ,@(for/list ([a (machine-airs m)])
                `(sealed-air (tanks ,@(air-spec-tanks a))
                             (tube-volume ,(num "sealed-air #:tube" (air-spec-tube-volume a)))
                             (heat-loss ,(num "sealed-air #:heat-loss" (air-spec-heat-loss a)))
                             (heat-capacity ,(num "sealed-air #:heat-capacity" (air-spec-heat-capacity a)))
                             ,(loc->sexp (air-spec-loc a) root)))))

(define (write-machine-file m path #:root [root #f] #:from [from #f])
  (call-with-output-file path #:exists 'truncate/replace
    (λ (out)
      (fprintf out ";; Generated by #lang heroic~a. Do not edit: change the Racket source and rebuild.\n"
               (if from (format " from ~a" from) ""))
      ;; One clause per line keeps the files readable and their diffs small.
      (define sexp (machine->sexp m #:root root))
      (fprintf out "(machine ~s" (cadr sexp))
      (for ([clause (cddr sexp)])
        (fprintf out "\n  ~s" clause))
      (fprintf out ")\n"))))

;; ---------------------------------------------------------------------------
;; Maps (issue #37): the .map file the C# Terrain reads.
;; (map NAME (origin X0 Z0) (cell C) (size NX NZ) (edges open|closed) (roughness N)
;;   (soils (MATERIAL RATE) ...) (source ID X Z FLOW) ... (heights ...) (soil K ...) (srcloc ...))
;; Heights are written to 0.1 mm, one row of the grid per line; soils as
;; indices into (soils ...), or one index if the whole map is one soil.
(define (map->sexp m #:root [root #f])
  (define name (ground-map-name m))
  (define soils
    (remove-duplicates (append (map car (ground-map-infiltration m)) (vector->list (ground-map-soil m)))))
  ;; each soil's strength (issue #44): cohesion from the map, friction (tan of repose) and density from materials.rktd
  (define (cohesion s)
    (cond [(assq s (or (ground-map-cohesion m) '())) => (λ (e) (num (format "map ~a #:cohesion" name) (cadr e)))] [else 0.0]))
  (define (field s k) (num (format "soil ~a ~a" s k) (material-field (assq s (material-table)) k)))
  ;; its grains (issue #53): size (0: nothing flowing water can lift) and density (quartz, 2650, unless given)
  (define (grain s)
    (cond [(assq s (or (ground-map-grain m) '()))
           => (λ (e) (list (num "map #:grain" (cadr e)) (num "map #:grain" (if (pair? (cddr e)) (caddr e) 2650))))]
          [else (list 0.0 2650.0)]))
  (define (rate s)
    (cond [(assq s (ground-map-infiltration m)) => (λ (e) (num (format "map ~a #:infiltration" name) (cadr e)))]
          [else 0.0]))
  (define soil-index (for/vector ([s (ground-map-soil m)]) (index-of soils s)))
  `(map ,name
        (origin ,@(for/list ([v (ground-map-origin m)]) (num "map #:origin" v)))
        (cell ,(num "map #:cell" (ground-map-cell m)))
        (size ,(ground-map-nx m) ,(ground-map-nz m))
        (edges ,(ground-map-edges m))
        (roughness ,(num "map #:roughness" (ground-map-roughness m)))
        ,@(if (ground-map-settle m) '((settle #t)) '())
        (soils ,@(for/list ([s soils]) (list* s (rate s) (cohesion s) (field s 'friction) (field s 'density) (grain s))))
        ,@(for/list ([s (ground-map-sources m)])
            `(source ,(map-source-id s) ,(num "source #:at" (map-source-x s)) ,(num "source #:at" (map-source-z s))
                     ,(num "source #:flow" (map-source-flow s))))
        (heights ,@(for/list ([h (ground-map-heights m)]) (/ (round (* (num "map height" h) 10000.0)) 10000.0)))
        (soil ,@(if (for/and ([k soil-index]) (= k (vector-ref soil-index 0)))
                    (list (vector-ref soil-index 0))
                    (vector->list soil-index)))
        ,(loc->sexp (ground-map-loc m) root)))

(define (write-map-file m path #:root [root #f] #:from [from #f])
  (define sexp (map->sexp m #:root root))
  (define nx (ground-map-nx m))
  (call-with-output-file path #:exists 'truncate/replace
    (λ (out)
      (fprintf out ";; Generated by #lang heroic~a. Do not edit: change the Racket source and rebuild.\n"
               (if from (format " from ~a" from) ""))
      (fprintf out "(map ~s" (cadr sexp))
      (for ([clause (cddr sexp)])
        (case (car clause)
          [(heights soil)
           (fprintf out "\n  (~a" (car clause))
           (for ([v (cdr clause)] [k (in-naturals)])
             (when (and (eq? (car clause) 'heights) (zero? (modulo k nx))) (fprintf out "\n   "))
             (fprintf out " ~a" v))
           (fprintf out ")")]
          [else (fprintf out "\n  ~s" clause)]))
      (fprintf out ")\n"))))
