#lang racket/base
;; Turns a machine value into the .machine format: plain S-expressions
;; with every number a finite flonum, so the C# reader never meets exact
;; rationals (3/100) or infinities.
(require racket/path "machine.rkt")
(provide machine->sexp write-machine-file)

(define (num who v)
  (unless (and (real? v) (rational? v))
    (error 'machine->sexp "~a must be a finite number, got ~e" who v))
  (exact->inexact v))

(define (value who v)
  (if (or (boolean? v) (symbol? v) (string? v)) v (num who v)))

(define (loc->sexp loc root)
  (define file (vector-ref loc 0))
  (define shown
    (if (and root (absolute-path? file))
        (path->string (find-relative-path (simple-form-path root) (simple-form-path file)))
        file))
  `(srcloc ,shown ,(vector-ref loc 1) ,(vector-ref loc 2)))

(define (part->sexp p root)
  (define id (part-id p))
  `(part ,id ,(part-kind p)
         (material ,(part-material p))
         (at ,@(for/list ([x (part-at p)]) (num (format "~a position" id) x)))
         (props ,@(for/list ([kv (part-props p)])
                    (list (car kv) (value (format "~a #:~a" id (car kv)) (cdr kv)))))
         (ports ,@(for/list ([pt (part-ports p)])
                    (list (port-spec-name pt) (port-spec-kind pt)
                          (num (format "~a port height" id) (port-spec-height pt)))))
         ,(loc->sexp (part-loc p) root)))

;; root: when given, source paths are written relative to it.
(define (machine->sexp m #:root [root #f])
  `(machine ,(machine-name m)
            ,@(if (machine-source m) `((source ,(machine-source m))) '())
            ,@(for/list ([p (machine-parts m)]) (part->sexp p root))
            ,@(for/list ([p (machine-pipes m)])
                `(pipe ,(pipe-spec-id p)
                       (from ,@(pipe-spec-from p))
                       (to ,@(pipe-spec-to p))
                       (conductance ,(num (format "pipe ~a conductance" (pipe-spec-id p))
                                          (pipe-spec-conductance p)))
                       (jet ,(pipe-spec-jet? p))
                       ,(loc->sexp (pipe-spec-loc p) root)))
            ,@(for/list ([c (machine-connects m)])
                `(connect ,(connect-spec-from c) ,(connect-spec-to c)
                          ,(loc->sexp (connect-spec-loc c) root)))
            ,@(for/list ([a (machine-airs m)])
                `(sealed-air (tanks ,@(air-spec-tanks a))
                             (tube-volume ,(num "sealed-air #:tube" (air-spec-tube-volume a)))
                             ,(loc->sexp (air-spec-loc a) root)))))

(define (write-machine-file m path #:root [root #f] #:from [from #f])
  (call-with-output-file path #:exists 'truncate/replace
    (λ (out)
      (fprintf out ";; Generated by #lang heroic~a. Do not edit: change the Racket source and rebuild.\n"
               (if from (format " from ~a" from) ""))
      ;; One clause per line keeps the files readable and their diffs small.
      (define sexp (machine->sexp m #:root root))
      (fprintf out "(machine ~s" (cadr sexp))
      (for ([clause (cddr sexp)])
        (fprintf out "\n  ~s" clause))
      (fprintf out ")\n"))))
